export const monthsEnum = {
  January: { days: 31, name: "January" },
  February: { days: 28, name: "February" },
  March: { days: 31, name: "March" },
  April: { days: 30, name: "April" },
  May: { days: 31, name: "May" },
  June: { days: 30, name: "June" },
  July: { days: 31, name: "July" },
  August: { days: 31, name: "August" },
  September: { days: 30, name: "September" },
  October: { days: 31, name: "October" },
  November: { days: 30, name: "November" },
  December: { days: 31, name: "December" },
};
export const monthIndexEnum = {
  0: "January",
  1: "February",
  2: "March",
  3: "April",
  4: "May",
  5: "June",
  6: "July",
  7: "August",
  8: "September",
  9: "October",
  10: "November",
  11: "December",
};
export const monthEnum = {
  January: 0,
  February: 1,
  March: 2,
  April: 3,
  May: 4,
  June: 5,
  July: 6,
  August: 7,
  September: 8,
  October: 9,
  November: 10,
  December: 11,
};
export const weekEnum = {
  0: "Sunday",
  1: "Monday",
  2: "Tuesday",
  3: "Wednesday",
  4: "Thursday",
  5: "Friday",
  6: "Saturday",
};
export const weekIndexOfEnum = {
  Sunday: 0,
  Monday: 1,
  Tuesday: 2,
  Wednesday: 3,
  Thursday: 4,
  Friday: 5,
  Saturday: 6,
};
